name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
        releaseCreated: ${{ steps.release.outputs.release_created }}
    steps:
        - uses: google-github-actions/release-please-action@v3
          id: release
          with:
            release-type: node
            package-name: catapulta-verify
            pull-request-header: "I have created a release"

  release-node:
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releaseCreated }}
    needs:
        - release-please
    steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v1
        - name: Install dependencies
          run: bun install
        - name: Build
          run: bun run build
        - name: Publish
          run: npm publish --access=public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}